language: c
compiler:
- clang
- gcc
env:
- BRANCH=trunk
- BRANCH=branches/4.2
- BRANCH=branches/4.0
sudo: true
before_install:
- sudo apt install subversion
- sudo apt install libyaml-dev
before_script:
- svn export svn://svn.zabbix.com/$BRANCH zabbix
- cd zabbix
- ./bootstrap.sh
- ./configure
- cd -
script:
- ZABBIX_SOURCE=zabbix CFLAGS='-Wall -Wextra -Wpedantic -g -O2' make
